root: true
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2022
  sourceType: 'module'
rules:
  no-useless-escape: 0
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-unused-vars':
    - 2
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  '@typescript-eslint/ban-ts-comment': 0
  '@typescript-eslint/no-this-alias': 0
  '@typescript-eslint/no-var-requires': 0
