root: true
plugins:
  - prettier
extends:
  - plugin:prettier/recommended
  - plugin:react/recommended
parser: babel-eslint
settings:
  react:
    version: "0.16"
env:
  browser: true
  es6: true
  mocha: true
  node: true
globals:
  CodeMirror: true
  it: true
  describe: true
rules:
  no-useless-escape: 0
  prettier/prettier:
    - 2
    -
      trailingComma: none
      singleQuote: true
      semi: false
  prefer-const: 2
  no-unused-vars:
    - 2
    -
      argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  react/display-name: 0
